site_name: Worldbuilding
site_url: https://jaw-bone6.github.io/worldbuilding/
repo_url: https://github.com/Jaw-bone6/worldbuilding
nav:
  - Basics:
    - vilix.md
    - soul.md
    - dimension.md
  - Vilins:
    - human.md
    - unbound_soul.md
    - thermovore.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    scheme: slate
    primary: deep purple
  logo: assets/logo2.png
  favicon: assets/favicon.ico
plugins:
  - tags
  - search
