site_name: Worldbuilding
nav:
  - Home: index.md
  - Fundamentals:
    - vilix.md
    - dimension.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    scheme: slate
    primary: deep purple
  logo: assets/logo.png
